version: '3'

tasks:
  init:
    cmds:
      - pre-commit install --hook-type commit-msg
      - pre-commit install

  crd-extract:
    dir: ./scripts
    cmds:
      - |
        if [ ! -d .venv ]; then
          python3 -m venv .venv
        fi
      - |
        source .venv/bin/activate
        ./crd-extractor.sh
